### ISSUE TITLE
Rename organization to "LibreSprite"

### ISSUE THREAD

**Issue by Symbian9** [aseprite-gpl/aseprite-gpl#20] opened 2018-05-04 22:28 UTC
### TODO

- [ ] ~~https://github.com/aseprite-gpl~~ → http://github.com/LibreSprite

### REFERENCE

- https://github.com/aseprite-gpl/aseprite/issues/8
- https://github.com/aseprite-gpl/aseprite/issues/10

**Comment by akien-mga** [comment] 2018-06-03 09:05
Duplicate of #8.

**Closed by akien-mga** 2018-06-03 09:05 UTC
