### ISSUE TITLE
Rename repository to "LibreSprite"

### ISSUE THREAD

**Issue by Symbian9** [aseprite-gpl/aseprite-gpl#21] opened 2018-05-04 22:31 UTC
### TODO

- [ ] ~~https://github.com/aseprite-gpl/aseprite~~ → http://github.com/LibreSprite/LibreSprite

### RELATED

- https://github.com/aseprite-gpl/aseprite/issues/20

### REFERENCE

- https://github.com/aseprite-gpl/aseprite/issues/8
- https://github.com/aseprite-gpl/aseprite/issues/10

**Comment by akien-mga** [comment] 2018-06-03 09:05
Duplicate of #8.

**Closed by akien-mga** 2018-06-03 09:05 UTC
